#!/bin/bash
 
#PBS -N SLuiceGate
#PBS -W group_list=u75
#PBS -l nodes=1:ppn=1
#PBS -l vmem=48gb
#PBS -l walltime=200:00:00
#PBS -j oe
#PBS -M x.barthelemy@wrl.unsw.edu.au
#PBS -m abe
#PBS -o OUTPUT.txt 

cd $PBS_O_WORKDIR
gerris2D Sluice-Gate-MultiDomain.gfs

